version: '3.7'
services:
  reveries:
    build: 
      context: .
      dockerfile: dev.dockerfile
    container_name: reveries_app
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .env:/usr/src/app/.env
      - /usr/src/app/node_modules