version: '3.7'
services:
  db:
    image: "postgres:12"
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: hello
    ports:
      - "5432:5432"